accounts/views.py
import re

from datetime import timedelta
from http import HTTPStatus
from requests.exceptions import ConnectionError
from werkzeug.exceptions import InternalServerError
from authlib.integrations.flask_client import OAuthError
from authlib.integrations.base_client.errors import TokenExpiredError

from flask import Blueprint, Response
from flask import abort, current_app, render_template, request, redirect, url_for, flash
from flask_babel import lazy_gettext as _
from flask_login import current_user, login_required, login_user, logout_user

from accounts.decorators import authentication_redirect, guest_user_exempt
from accounts.email_utils import (
    send_reset_password,
    send_reset_email,
)
from accounts.extensions import database as db, limiter, oauth
from accounts.models import User, OAuthProvider
from accounts.forms import (
    RegisterForm,
    LoginForm,
    ForgotPasswordForm,
    ResetPasswordForm,
    ChangePasswordForm,
    ChangeEmailForm,
    EditUserProfileForm,
    DeleteAccountForm,
)
from accounts.utils import (
    get_unique_id,
    get_username_from_email,
    download_and_save_image_from_url,
)


"""
This accounts blueprint defines routes and templates related to user management
within our application.
"""
accounts = Blueprint("accounts", __name__, template_folder="templates")


@accounts.route("/login_as_guest", methods=["GET", "POST"])
@authentication_redirect
@limiter.limit("3/minute", methods=["POST"])
def login_guest_user() -> Response:
    """
    Log in as a guest user with limited access.

    :return: Redirects to the homepage on success or the login page on failure.
    """

    if request.method == "POST":
        # Fetch the predefined guest user instance by username.
        test_user = User.get_user_by_username(username="testuser")

        if test_user:
            # Log in the guest user with a session duration of (1 day) only.
            login_user(test_user, remember=True, duration=timedelta(days=1))

            flash(_("You are logged in as a Guest User."), "success")
            return redirect(url_for("accounts.index"))

        flash(_("Test user not found."), "error")
        return redirect(url_for("accounts.login"))

    # Return a 404 error if accessed via GET
    return abort(HTTPStatus.NOT_FOUND)


@accounts.route("/register", methods=["GET", "POST"])
@authentication_redirect
@limiter.limit("3/minute", methods=["POST"])
def register() -> Response:
    """
    Handling user registration.
    If the user is already authenticated, they are redirected to the index page.

    This view handles both GET and POST requests:
    - GET: Renders the registration form and template.
    - POST: Processes the registration form, creates a new user, and sends a confirmation email.

    :return: Renders the registration template on GET request
    or redirects to login after successful registration.
    """
    form = RegisterForm()

    if form.validate_on_submit():
        username = form.data.get("username")
        first_name = form.data.get("first_name")
        last_name = form.data.get("last_name")
        email = form.data.get("email")
        password = form.data.get("password")

        # Attempt to create a new user and save to the database.
        user = User.create(
            username=username,
            first_name=first_name,
            last_name=last_name,
            email=email,
            password=password,
        )

        # Sends account confirmation mail to the user.
        user.send_confirmation()

        flash(
            _("A confirmation link sent to your email. Please verify your account."),
            "success",
        )
        return redirect(url_for("accounts.login"))

    return render_template("register.html", form=form)


@accounts.route("/login", methods=["GET", "POST"])
@authentication_redirect
@limiter.limit("5/minute", methods=["POST"])
def login() -> Response:
    """
    Handling user login functionality.
    If the user is already authenticated, they are redirected to the index page.

    This view handles both GET and POST requests:
    - GET: Renders the login form and template.
    - POST: Validates the form and authenticates the user.

    :return: Renders the login template on GET request or redirects based on the login status.
    """
    form = LoginForm()  # A form class for Login Account.

    if form.validate_on_submit():
        username = form.data.get("username", None)
        password = form.data.get("password", None)
        remember = form.data.get("remember", True)

        # Attempt to authenticate the user from the database.
        user = User.authenticate(username=username, password=password)

        if not user:
            flash(_("Invalid username or password. Please try again."), "error")
        else:
            if not user.is_active:
                # User account is not active, send confirmation email.
                user.send_confirmation()

                flash(
                    _(
                        "Your account is not activate. We sent a confirmation link to your email"
                    ),
                    "error",
                )
                return redirect(url_for("accounts.login"))

            # Log the user in and set the session to remember the user for (15 days).
            login_user(user, remember=remember, duration=timedelta(days=15))

            flash(_("You are logged in successfully."), "success")
            return redirect(url_for("accounts.index"))

        return redirect(url_for("accounts.login"))

    return render_template("login.html", form=form)


@accounts.route("/account/confirm", methods=["GET", "POST"])
def confirm_account() -> Response:
    """
    Handling account confirmation request via a token.
    If the token is valid and not expired, the user is activated.

    This view handles both GET and POST requests:
    - GET: Renders the account confirmation template.
    - POST: Activates the user account if the token is valid,
            logs the user in, and redirects to the index page.

    :return: Renders the confirmation template on GET request,
    redirects to login or index after POST.
    """
    token: str = request.args.get("token", None)

    # Verify the provided token and return token instance.
    auth_token = User.verify_token(
        token=token, salt=current_app.config["SALT_ACCOUNT_CONFIRM"]
    )

    if auth_token:
        # Retrieve the user instance associated with the token by providing user ID.
        user = User.get_user_by_id(auth_token.user_id, raise_exception=True)

        if request.method == "POST":
            try:
                # Activate the user's account and expire the token.
                user.active = True
                auth_token.expire = True

                # Commit changes to the database.
                db.session.commit()
            except Exception as e:
                # Handle database error that occur during the account activation.
                raise InternalServerError

            # Log the user in and set the session to remember the user for (15 days).
            login_user(user, remember=True, duration=timedelta(days=15))

            flash(
                _(f"Welcome {user.username}, You're registered successfully."),
                "success",
            )
            return redirect(url_for("accounts.index"))

        return render_template("confirm_account.html", token=token)

    # If the token is invalid, return a 404 error
    return abort(HTTPStatus.NOT_FOUND)


@accounts.route("/logout", methods=["GET", "POST"])
@login_required
def logout() -> Response:
    """
    Logs out the currently authenticated user
    and redirect them to the login page.

    :return: A redirect response to the login page with a success flash message.
    """
    # Log out the user and clear the session.
    logout_user()

    flash(_("You're logout successfully."), "success")
    return redirect(url_for("accounts.login"))


@accounts.route("/forgot/password", methods=["GET", "POST"])
@guest_user_exempt
@limiter.limit("3/minute", methods=["POST"])
def forgot_password() -> Response:
    """
    Handling forgot password requests by validating the provided email
    and sending a password reset link if the email is registered.

    This view handles both GET and POST requests:
    - GET: Renders the forgot password form and template.
    - POST: Validates the email and sends a reset link if the email exists in the system.

    :return: Renders the forgot password form on GET,
    redirects to login on success, or reloads the form on failure.
    """
    form = ForgotPasswordForm()

    if form.validate_on_submit():
        email = form.data.get("email")

        # Attempt to find the user by email from the database.
        user = User.get_user_by_email(email=email)

        if user:
            # Send a reset password link to the user's email.
            send_reset_password(user)

            flash(
                _("A reset password link sent to your email. Please check."), "success"
            )
            return redirect(url_for("accounts.login"))

        flash(_("Email address is not registered with us."), "error")
        return redirect(url_for("accounts.forgot_password"))

    return render_template("forgot_password.html", form=form)


@accounts.route("/password/reset", methods=["GET", "POST"])
@limiter.limit("5/minute", methods=["POST"])
def reset_password() -> Response:
    """
    Handling password reset requests.

    This function allows users to reset their password by validating a token
    and ensuring the new password meets security criteria.

    This view handles both GET and POST requests:
    - GET: Renders the reset password form and template, if the token is valid.
    - POST: Validates the form, checks password strength, and updates the user's password.

    :return: Renders the reset password form on GET,

accounts/templates/base.html
{% from 'bootstrap5/utils.html' import render_icon %}
{% from 'bootstrap5/nav.html' import render_nav_item %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="description" content="A simple user authentication system built with Flask and SQLAlchemy." />
  <link rel="shortcut icon" href="{{ url_for('static', filename='assets/favicon.ico') }}" type="image/x-icon">
  <title>{{ title }} - Flask Authentication System</title>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
  {{ bootstrap.load_css() }}
  {% block styles %}{% endblock %}
</head>

<body>
  <!-- navbar -->
  <nav class="navbar navbar-expand-md navbar-dark bg-dark static-top py-1">
    <div class="container-fluid px-lg-4">
      <a class="navbar-brand" href="{{ url_for('accounts.index') }}">
        <div class="d-flex p-2 rounded-3" style="border: 1px solid #fff;">
          <img class="w-100 me-2" src="{{ url_for('static', filename='assets/images/logo.png') }}" alt="logo"
            style="height: 25px;">
          <h5 class="text-uppercase m-0">Flask Auth</h5>
        </div>
      </a>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mainNavbar">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="mainNavbar">
        <ul class="navbar-nav">
          {{ render_nav_item('accounts.index', _('Home') ) }}
          {% if current_user.is_authenticated %}
          {{ render_nav_item('accounts.profile', _('Profile')) }}
          {{ render_nav_item('accounts.change_email', _('Reset Email') ) }}
          {{ render_nav_item('accounts.change_password', _('Change Password') ) }}
          {{ render_nav_item('accounts.settings', _('Settings') ) }}
          {% endif %}

          <!-- theme selector dropdown -->
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="bi bi-palette-fill me-2"></i>{{ _('Theme') }}</a>
            <ul class="dropdown-menu">
              {% for theme in config["BOOTSTRAP_BOOTSWATCH_THEMES"] %}
              <li>
                <a class="dropdown-item d-flex" href="{{ url_for('change_theme', theme=theme) }}">
                  {{ theme.capitalize() }}
                  {% if session.get('_theme_preference', none) is none and theme == 'pulse' %}
                  <i class="bi bi-check-circle-fill ms-auto"></i>
                  {% else %}
                  {% if session.get('_theme_preference') == theme %}
                  <i class="bi bi-check-circle-fill ms-auto"></i>
                  {% endif %}{% endif %}
                </a>
              </li>
              {% endfor %}
            </ul>
          </li>

          <!-- language selector dropdown -->
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="bi bi-translate me-2"></i>{{ _('Language') }}</a>
            <ul class="dropdown-menu">
              {% set flags = { "en": "🇺🇸", "es": "🇪🇸", "fr": "🇫🇷", "de": "🇩🇪" } %}
              {% for lang in config["LANGUAGES"] %}
              <li class="">
                <a class="dropdown-item d-flex" href="{{ url_for('change_lang', lang=lang) }}">
                  {{ flags.get(lang, "🌐") }} {{ lang }}
                  {% if session.get('_lang_preference') == lang %}
                  <i class="bi bi-check-circle-fill ms-auto"></i>
                  {% endif %}
                </a>
              </li>
              {% endfor %}
            </ul>
          </li>

        </ul>
        <ul class="navbar-nav ms-auto my-2">
          {% if not current_user.is_authenticated %}
          {{ render_nav_item('accounts.login', _('Login')) }}
          <li class="nav-item my-2 my-md-0 ms-md-2">
            <a class="btn btn-outline-light" href="{{ url_for('accounts.register') }}">{{ _("Signup") }}</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="btn btn-outline-light" href="{{ url_for('accounts.logout') }}">{{ _("Logout") }}</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  {% block body %} {% endblock %}

  <!-- Footer -->
  <footer class="text-center text-lg-start text-dark">
    <div class="d-flex justify-content-between p-4" style="background-color: rgba(170, 170, 170, 0.2)">
      <a class="text-body" href="https://github.com/anuraagnagar/flask-user-authentication" target="_blank">
        <button class="btn btn-secondary">{{ _("Source Code") }}
          <span class="my-auto">{{ render_icon('github') }}</span></button>
      </a>
      <p class="text-muted m-0">© 2025 FlaskAuth</p>
    </div>
  </footer>

  {% block scripts %}
  <!-- Optional JavaScript -->
  {{ bootstrap.load_js() }}
  {% endblock %}
</body>

</html>

accounts/templates/change_email.html
{% set title = _("Reset Email Address") %}

{% extends "base.html" %}
{% from 'bootstrap5/form.html' import render_field %}
{% from 'bootstrap5/utils.html' import render_messages %}

{% block body %}

<main class="my-5">
    <div class="container">
        <div class="row justify-content-center">
            <section class="col-sm-11 col-md-8 col-lg-6 col-xl-5">
                <div class="card shadow-sm mb-4">
                    <div class="p-4">
                        <form action="{{ url_for('accounts.change_email') }}" method="post">
                            <div class="mb-4">
                                <h2 class="card-title text-center">{{ _('Change Your Email Address') }}</h2>
                                {{ render_messages() }}
                                <p class="text-muted">{{ _('To change your email enter new email address and you will
                                    receive an confirmation link to confirm your email.') }}</p>
                            </div>
                            {{ form.hidden_tag() }}
                            {{ render_field(form.email, placeholder=_("Enter email address"), autofocus="true") }}
                            {{ render_field(form.remember) }}
                            {{ render_field(form.submit, class='w-100 mb-2') }}
                        </form>
                    </div>
                </div>
                <p class="text-center">
                    <a href="{{ url_for('accounts.index') }}" class="text-decoration-none">
                        {{ _('Back to Home') }}</a>
                </p>
            </section>
        </div>
    </div>
</main>

{% endblock %}

accounts/templates/confirm_account.html
{% set title = _("Confirm Account") %}

{% extends "base.html" %}
{% from 'bootstrap5/utils.html' import render_messages %}

{% block body %}

<div class="my-5">
    <div class="container">
        <div class="row justify-content-center">
            {{ render_messages(dismissible=True, dismiss_animate=True) }}
            <div class="col-sm-10 col-md-8 col-lg-7 col-xl-7">
                <div class="card my-5">
                    <div class="card-body">
                        <form action="{{ url_for('accounts.confirm_account', token=token) }}" method="post">
                            <div class="my-5">
                                <h5 class="text-center">{{ _('To confirm your account please click the button below.')
                                    }}
                                </h5>
                                <div class="d-flex justify-content-center my-4">
                                    <input id="csrf_token" type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                                    <input id="submit" type="submit" role="button" name="submit" class="btn btn-primary"
                                        value="Confirm Your Account" />
                                </div>
                                <p class="text-center">
                                    <a class="text-decoration-none" href="{{ url_for('accounts.login') }}">
                                        {{ _('back to login') }}</a>
                                </p>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

accounts/templates/error.html
{% extends "base.html" %}
{% block title %}404 Not Found{% endblock %}

{% block body %}

<div class="my-3">
    <div class="container">
        <div class="h-100vh">
            <div class="row align-items-center" style="height: 80vh;">
                <h1 class="text-center"><span class="text-primary">404 </span>Page Not Found</h1>
            </div>
        </div>
    </div>
</div>

{% endblock %}

accounts/templates/forget_password.html
{% extends "base.html" %}
{% from 'bootstrap5/form.html' import render_field %}
{% from 'bootstrap5/utils.html' import render_messages %}
{% block title %}Forgot Password{% endblock %}

{% block body %}
<main class="my-5">
    <div class="container">
        <div class="row justify-content-center">
            <section class="col-sm-11 col-md-8 col-lg-6 col-xl-5">
                <div class="card shadow-sm border-0 mb-4">
                    <div class="p-4">
                        <form action="{{ url_for('accounts.forgot_password') }}" method="post">
                            <div class="mb-4">
                                <h2 class="card-title text-center mb-3">Forgot Password</h2>
                                {{ render_messages() }}
                                <p>Reset password enter your email address and you will receive an email
                                    with further instructions on how to reset your password.</p>
                            </div>
                            {{ form.csrf_token() }}
                            {{ render_field(form.email, placeholder="Enter your email address", autofocus="true") }}
                            {{ render_field(form.remember) }}
                            {{ render_field(form.submit, class="w-100") }}
                        </form>
                    </div>
                </div>
                {% if not current_user.is_authenticated %}
                <p class="text-center">Don't Have an account?
                    <a href="{{ url_for('accounts.register') }}" class="text-decoration-none">Sign Up</a>
                </p>
                {% else %}
                <p class="text-center">
                    <a href="{{ url_for('accounts.index') }}" class="text-decoration-none">Back to Home</a>
                </p>
                {% endif %}
            </section>
        </div>
    </div>
</main>
{% endblock %}

accounts/templates/forgot_password.html
{% set title = _("Forgot Password") %}

{% extends "base.html" %}
{% from 'bootstrap5/form.html' import render_field %}
{% from 'bootstrap5/utils.html' import render_messages %}

{% block body %}
<main class="my-5">
    <div class="container">
        <div class="row justify-content-center">
            <section class="col-sm-11 col-md-8 col-lg-6 col-xl-5">
                <div class="card shadow-sm mb-4">
                    <div class="p-4">
                        <form action="{{ url_for('accounts.forgot_password') }}" method="post">
                            <div class="mb-4">
                                <h2 class="card-title text-center mb-3">{{ _("Forgot Password") }}</h2>
                                {{ render_messages() }}
                                <p>{{ _('Reset password enter your email address and you will receive an email with
                                    further instructions on how to reset your password.') }}</p>
                            </div>
                            {{ form.hidden_tag() }}
                            {{ render_field(form.email, placeholder=_('Enter your email address'),
                            autofocus="true")
                            }}
                            {{ render_field(form.remember) }}
                            {{ render_field(form.submit, class="w-100") }}
                        </form>
                    </div>
                </div>
                {% if not current_user.is_authenticated %}
                <p class="text-center">{{ _("Don't Have an account?") }}
                    <a href="{{ url_for('accounts.register') }}" class="text-decoration-none">{{ _('Sign Up') }}</a>
                </p>
                {% else %}
                <p class="text-center">
                    <a href="{{ url_for('accounts.index') }}" class="text-decoration-none">{{ _('Back to Home') }}</a>
                </p>
                {% endif %}
            </section>
        </div>
    </div>
</main>
{% endblock %}

accounts/templates/login.html
{% set title = _("Login") %}

{% extends "base.html" %}
{% from 'bootstrap5/form.html' import render_field %}
{% from 'bootstrap5/utils.html' import render_messages %}
{% block styles %}
<style>
    .g-recaptcha {
        transform: scale(0.9);
        transform-origin: 0 0;
    }
</style>
{% endblock %}

{% block body %}
<main class="my-5">
    <div class="container">
        <div class="row justify-content-center">
            <section class="col-sm-10 col-md-8 col-lg-6 col-xl-5">
                <div class="card shadow-sm mb-4">
                    <div class="p-4">
                        <div class="mb-3">
                            <h2 class="card-title text-center">{{ _('Login Account') }}</h2>
                        </div>
                        {{ render_messages() }}
                        <form action="{{ url_for('accounts.google_login') }}" method="post">
                            <div class="form-outline">
                                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                                <input type="hidden" name="action" value="login">
                                <button class="btn btn-outline-primary w-100" type="submit">
                                    <i class="bi bi-google me-2"></i>{{ _('Login with Google') }}
                                </button>
                            </div>
                        </form>
                        <div class="main-divider main-divider-horizontal my-3" role="separator">
                            <span>or</span>
                        </div>
                        <form action="{{ url_for('accounts.login') }}" method="post">
                            {{ form.hidden_tag() }}
                            {{ render_field(form.username, placeholder=_("Enter username or email"), autofocus="true")
                            }}
                            {{ render_field(form.password, placeholder=_("Enter your password")) }}
                            <div style="width: 100%; display: flex; justify-content: center;">
                                {{ render_field(form.recaptcha) }}
                            </div>
                            {{ render_field(form.remember, checked="true") }}
                            {{ render_field(form.submit, class="w-100 mb-3") }}
                            <p class="text-center">
                                <a href="{{ url_for('accounts.forgot_password') }}">{{ _('Forgot Password?') }}</a>
                            </p>
                        </form>
                        <div class="main-divider main-divider-horizontal my-3" role="separator">
                            <span>or</span>
                        </div>
                        <form action="{{ url_for('accounts.login_guest_user') }}" method="post">
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                            <input class="btn btn-outline-primary w-100" type="submit" name="submit"
                                value="{{ _('Login as Guest User') }}">
                        </form>
                    </div>
                </div>
                <p class="text-center">{{ _("Don't Have an account?") }}
                    <a href="{{ url_for('accounts.register') }}" class="text-decoration-none">{{ _("Sign Up") }}</a>
                </p>
            </section>
        </div>
    </div>
</main>

{% endblock %}

accounts/templates/register.html
{% set title = _("Register") %}

{% extends "base.html" %}
{% from 'bootstrap5/form.html' import render_field %}
{% from 'bootstrap5/utils.html' import render_messages %}
{% block styles %}
<style>
  .g-recaptcha {
    transform: scale(0.9);
    transform-origin: 0 0;
  }
</style>
{% endblock %}

{% block body %}

<main class="my-5">
  <div class="container">
    <div class="row justify-content-center">
      <section class="col-sm-11 col-md-8 col-lg-6 col-xl-5">
        <div class="card shadow-sm mb-4">
          <div class="p-4">
            <div class="mb-3">
              <h2 class="card-title text-center">{{ _('Create Account') }}</h2>
              <p class="text-center">{{ _('Get started with your free account') }}</p>
            </div>
            {{ render_messages() }}
            <form action="{{ url_for('accounts.google_login') }}" method="post">
              <div class="form-outline">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                <input type="hidden" name="action" value="register">
                <button class="btn btn-outline-primary w-100" type="submit">
                  <i class="bi bi-google me-2"></i>{{ _('Continue with Google') }}
                </button>
              </div>
            </form>
            <div class="main-divider main-divider-horizontal my-3" role="separator">
              <span>or</span>
            </div>
            <form action="{{ url_for('accounts.register') }}" method="post">
              {{ form.hidden_tag() }}
              {{ render_field(form.username, placeholder=_('Enter your username'), autofocus="true") }}
              <div class="row">
                <div class="col">
                  {{ render_field(form.first_name, placeholder=_('First name')) }}
                </div>
                <div class="col">
                  {{ render_field(form.last_name, placeholder=_('Last name')) }}
                </div>
              </div>
              {{ render_field(form.email, placeholder=_('Enter your email')) }}
              {{ render_field(form.password, placeholder=_('Choose your password')) }}
              <div style="width: 100%; display: flex; justify-content: center;">
                {{ render_field(form.recaptcha) }}
              </div>
              {{ render_field(form.remember) }}
              {{ render_field(form.submit, class="w-100") }}
            </form>
          </div>
        </div>
        <p class="text-center">
          {{ _('Have an account?') }} <a href="{{ url_for('accounts.login') }}" class="text-decoration-none">
            {{ _('Log In') }}</a>
        </p>
      </section>
    </div>
  </div>
</main>

{% endblock %}

accounts/templates/reset_password.html
{% set title = _("Reset Password") %}

{% extends "base.html" %}
{% from 'bootstrap5/form.html' import render_field %}
{% from 'bootstrap5/utils.html' import render_messages %}

{% block body %}

<main class="my-5">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-11 col-md-8 col-lg-6 col-xl-5">
                <div class="card shadow-sm mb-4">
                    <section class="p-4">
                        <form action="{{ url_for('accounts.reset_password', token=token) }}" method="post">
                            <div class="mb-4">
                                <h2 class="card-title text-center">{{ _('Reset Password') }}</h2>
                            </div>
                            {{ render_messages() }}
                            {{ form.hidden_tag() }}
                            {{ render_field(form.password, placeholder=_('Choose your password'), autofocus="true") }}
                            {{ render_field(form.confirm_password, placeholder=_('Re-type your password')) }}
                            {{ render_field(form.remember) }}
                            {{ render_field(form.submit, class="w-100 mb-2") }}
                        </form>
                    </section>
                </div>
                <p class="text-center">
                    {% if not current_user.is_authenticated %}
                    <a class="text-decoration-none" href="{{ url_for('accounts.login') }}">
                        {{ _('Back to Login') }}</a>
                    {% else %}
                    <a class="text-decoration-none" href="{{ url_for('accounts.index') }}">
                        {{ _('Back to Home') }}</a>
                    {% endif %}
                </p>
            </div>
        </div>
    </div>
</main>

{% endblock %}